name=input('Enter your name: ')
last_name=input('Enter your last name: ')
country=input('Enter your country: ')
fav_car=input('Enter fav car: ')
fav_color=input('Enter fav color: ')
print('hello my name is', name, 'my last name is', last_name,'i live in',  country, 'my fav car is', fav_car, 'my fav color is', fav_color)