x=int(input('Enter X: '))
y=int(input('Enter X: '))
print(x + y )
print(x - y)
print(x * y)
print(x // y)
print(x * y // 2)
print(x + y - 4)
print(x - y + 2)
print(x // y - 3)
print(x * y +7 )
print(x - y * 9 )